=== ISA-tools/isa-api/isatools/resources/schemas/isa_model_version_1_0_schemas/core/investigation_schema.json
{
    "id": "https://raw.githubusercontent.com/ISA-tools/isa-api/master/isatools/resources/schemas/isa_model_version_1_0_schemas/core/investigation_schema.json",
    "$schema": "http://json-schema.org/draft-04/schema",
    "title" : "ISA investigation schema",
    "description" : "JSON-schema representing an investigation in the ISA model",
    "type" : "object",
    "properties" : {
        "@id": { "type": "string", "format": "uri" },
        "@context": { "type": "string", "format": "uri"},
        "@type" : { "type": "string", "enum": ["Investigation"] },
        "filename": { "type" : "string"},
        "identifier" : { "type" : "string" },
        "title" : { "type" : "string"},
        "description" : { "type" : "string"},
        "submissionDate" : { "type" : "string", "format" : "date-time"},
        "publicReleaseDate" : { "type" : "string", "format" : "date-time"},
        "ontologySourceReferences" : {
            "type" : "array",
            "items" : {
                "$ref": "ontology_source_reference_schema.json#"
            }
        },
        "publications" : {
            "type" : "array",
            "items" : {
                 "$ref": "publication_schema.json#"

            }
        },
        "people" : {
            "type" : "array",
            "items" : {
                 "$ref": "person_schema.json#"

            }
        },
        "studies" : {
            "type" : "array",
            "items" : {
                 "$ref": "study_schema.json#"

            }
        },
        "comments" : {
            "type": "array",
            "items": {
                 "$ref": "comment_schema.json#"
            }
        }
    },
    "additionalProperties": false
}

=== ISA-tools/isa-api/tests/data/json/minimal_syntax.json
{
    "comments": [
        {
            "name": "",
            "value": ""
        }
    ],
    "description": "",
    "identifier": "",
    "ontologySourceReferences": [],
    "people": [],
    "publicReleaseDate": "",
    "publications": [],
    "studies": [
        {
            "@id": "",
            "assays": [
                {
                    "@id": "",
                    "characteristicCategories": [],
                    "dataFiles": [],
                    "filename": "",
                    "materials": {
                        "otherMaterials": [],
                        "samples": []
                    },
                    "measurementType": {
                        "annotationValue": "",
                        "termAccession": "",
                        "termSource": ""
                    },
                    "processSequence": [],
                    "technologyPlatform": "",
                    "technologyType": {
                        "annotationValue": "",
                        "termAccession": "",
                        "termSource": ""
                    },
                    "unitCategories": []
                }
            ],
            "characteristicCategories": [],
            "description": "",
            "factors": [],
            "filename": "",
            "identifier": "",
            "materials": {
                "otherMaterials": [],
                "samples": [],
                "sources": []
            },
            "people": [],
            "processSequence": [],
            "protocols": [],
            "publicReleaseDate": "",
            "publications": [],
            "studyDesignDescriptors": [],
            "submissionDate": "",
            "title": "",
            "unitCategories": []
        }
    ],
    "submissionDate": "",
    "title": ""
}

=== ISA-tools/isa-api/tests/data/json/unit/protocol_parameter_link.json
{
    "comments": [
        {
            "name": "",
            "value": ""
        }
    ],
    "description": "",
    "identifier": "",
    "ontologySourceReferences": [],
    "people": [],
    "publicReleaseDate": "",
    "publications": [],
    "studies": [
        {
            "@id": "",
            "assays": [
                {
                    "@id": "",
                    "characteristicCategories": [],
                    "dataFiles": [],
                    "filename": "",
                    "materials": {
                        "otherMaterials": [],
                        "samples": []
                    },
                    "measurementType": {
                        "annotationValue": "",
                        "termAccession": "",
                        "termSource": ""
                    },
                    "processSequence": [
                        {
                            "@id": "#process/1",
                            "comments": [],
                            "date": "",
                            "executesProtocol": {
                                "@id": "#protocol/1"
                            },
                            "inputs": [],
                            "outputs": [],
                            "parameterValues": [
                                {
                                    "category": {
                                        "@id": "#parameter/1"
                                    },
                                    "value": ""
                                }
                            ],
                            "performer": ""
                        }
                    ],
                    "technologyPlatform": "",
                    "technologyType": {
                        "annotationValue": "",
                        "termAccession": "",
                        "termSource": ""
                    },
                    "unitCategories": []
                }
            ],
            "characteristicCategories": [],
            "description": "",
            "factors": [],
            "filename": "",
            "identifier": "",
            "materials": {
                "otherMaterials": [],
                "samples": [],
                "sources": []
            },
            "people": [],
            "processSequence": [],
            "protocols": [
                {
                    "@id": "#protocol/1",
                    "components": [],
                    "description": "",
                    "name": "",
                    "parameters": [
                        {
                            "@id": "#parameter/1",
                            "parameterName": {
                                "annotationValue": "",
                                "termAccession": "",
                                "termSource": ""
                            }
                        }
                    ],
                    "protocolType": {
                        "annotationValue": "",
                        "termAccession": "",
                        "termSource": ""
                    },
                    "uri": "",
                    "version": ""
                }
            ],
            "publicReleaseDate": "",
            "publications": [],
            "studyDesignDescriptors": [],
            "submissionDate": "",
            "title": "",
            "unitCategories": []
        }
    ],
    "submissionDate": "",
    "title": ""
}
